accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path("private_page_1/", views.private_page_1, name="private_page_1",),
    path("private_page_2/", views.private_page_2, name="private_page_2",),
    path("login", auth_views.LoginView.as_view(), name = "login",),
    path("logout", auth_views.LogoutView.as_view(), name = "logout",),
    path("password_change",auth_views.PasswordChangeView.as_view(success_url = "password_change_done"), name = "password_change",),
    path("password_change_done",auth_views.PasswordChangeDoneView.as_view(), name = "password_change_done",),
    path("password_reset", auth_views.PasswordResetView.as_view(success_url = "password_reset_done",), name = "password_reset",),
    path("password_reset_done", auth_views.PasswordResetDoneView.as_view(), name = "password_reset_done",),
    path("password_reset_confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(success_url = "/accounts/password_reset_complete"), name="password_reset_confirm"),
    path("password_reset_complete", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),


]

sgo/urls.py
# Importação dos módulos necessários para configurar as URLs.
from django.contrib import admin  # Módulo do admin do Django.
from django.urls import path, include  # Funções para definir caminhos e incluir outras configurações de URL.
from django.shortcuts import redirect  # Função para realizar redirecionamentos.


# Lista de padrões de URL para o projeto sgo.
urlpatterns = [
    # Define a URL 'admin/' que é tratada pelo site de administração do Django.
    path('admin/', admin.site.urls),

    # Define a URL raiz ('') para redirecionar automaticamente para a página de login.
    # Usa uma função lambda para redirecionar, sem necessidade de criar uma view separada.
    # Inclui as URLs padrões de autenticação do Django sob o caminho 'accounts/'.
    # Isso abrange URLs para login, logout, alteração de senha, etc.
    path('accounts/', include('django.contrib.auth.urls')),

    # Inclui as URLs da aplicação 'core', acessíveis sob o caminho 'home/'.
    # O arquivo 'core.urls' deve definir suas próprias URLs específicas da aplicação.
    path('', include('core.urls')),

    path("", include('core.urls')),
    path("accounts/", include('accounts.urls', namespace='accounts')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms

class LoginUserForm(forms.Form):
    username= forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class LoginForm(forms.Form):
    email = forms.EmailField(max_length=100)
    cpf = forms.CharField(max_length=11)  # ou use o campo "CPF" apropriado

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from .forms import LoginUserForm 

@login_required
def private_page_1(request):
    return render(request, "accounts/private_page_1.html")

@login_required
def private_page_2(request):
    return render(request, "accounts/private_page_2.html")

accounts/templates/accounts/actions.html
<hr>

<p>
    <a href="{% url 'accounts:private_page_1' %}">Private page 1</a>
</p>
<p>
    <a href="{% url 'accounts:private_page_2' %}">Private page 2</a>
</p>
<p>
    <a href="{% url 'accounts:password_change' %}">Change password</a>
</p>
<p>
    <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
</p>

accounts/templates/accounts/private_page_1.html
<h1>Private page 1</h1>
<hr>
<p>
    <strong>User name</strong>: {{user.username}}
</p>
<p>
    <strong>E-mail</strong>: {{user.email}}
</p>
<p>
    <strong>Password</strong>: {{user.password}}
</p>

{% include 'accounts/actions.html' %}

accounts/templates/accounts/private_page_2.html
<h1>Private page 2</h1>

{% include 'accounts/actions.html' %}